Add workaround for strdup() conflict with C library macro
The -ffreestanding argument does not appear to have the same effect
as with GCC, and so providing our own strdup() is causing the build
to fail:

X86EmulatorPkg/main.c:190:7: error: expected identifier or '('
char *strdup(const char *s)
      ^
/usr/include/aarch64-linux-gnu/bits/string2.h:337:22: note: expanded from macro 'strdup'
                     ^
/usr/include/aarch64-linux-gnu/bits/string2.h:326:4: note: expanded from macro '__strdup'
  (__extension__ (__builtin_constant_p (s) && __string2_1bptr_p (s)           \
   ^

So as a workaround, let's #undef strdup if it is a macro, and expose
our strdup() as __strdup() in the object file.

Signed-off-by: Ard Biesheuvel <ard.biesheuvel@linaro.org>